import { describe, expect, test } from "bun:test";
import { existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SOUND_CATEGORIES, soundCapMs, type LibrarySound } from "../src/lib/overlays/soundLibrary";

const LIBRARY = new URL("../public/overlay/library/", import.meta.url);
const MANIFEST_PATH = fileURLToPath(new URL("sounds.json", LIBRARY));
/** The pack is generated by scripts/build-sound-library.py and committed on its own. Until it
 * is, there is nothing to check here, and the suite says so rather than failing. */
const PACK_BUILT = existsSync(MANIFEST_PATH);
if (!PACK_BUILT) {
  console.warn("sound library: no sounds.json yet; build the pack with scripts/build-sound-library.py");
}
const MANIFEST: LibrarySound[] = PACK_BUILT ? await Bun.file(MANIFEST_PATH).json() : [];
const ID = /^(chime|coin|jingle|arcade|whoosh|impact)-\d{2}$/;
/** The spec's ceiling for the whole pack. */
const MAX_TOTAL_BYTES = 6 * 1024 * 1024;

describe.skipIf(!PACK_BUILT)("bundled sound library", () => {
  test("36 sounds, six in each of the six categories", () => {
    expect(MANIFEST.length).toBe(36);
    for (const category of SOUND_CATEGORIES) {
      expect([category, MANIFEST.filter((s) => s.category === category).length]).toEqual([category, 6]);
    }
  });

  test("ids are unique and stable-shaped, and each names its own file", () => {
    expect(new Set(MANIFEST.map((s) => s.id)).size).toBe(MANIFEST.length);
    for (const s of MANIFEST) {
      expect([s.id, ID.test(s.id)]).toEqual([s.id, true]);
      expect(s.file).toBe(`sounds/${s.id}.ogg`);
      expect(s.name.length > 0 && s.source.startsWith("Kenney ")).toBe(true);
    }
  });

  test("every file exists and the pack stays inside its size budget", () => {
    let total = 0;
    for (const s of MANIFEST) {
      const path = fileURLToPath(new URL(s.file, LIBRARY));
      expect([s.file, existsSync(path)]).toEqual([s.file, true]);
      total += statSync(path).size;
    }
    expect(total).toBeGreaterThan(0);
    expect(total).toBeLessThanOrEqual(MAX_TOTAL_BYTES);
  });

  test("durations are within their category's cap", () => {
    for (const s of MANIFEST) {
      expect([s.id, s.durationMs > 0 && s.durationMs <= soundCapMs(s.category)]).toEqual([s.id, true]);
    }
  });

  test("the licence notes sit beside the manifest", () => {
    expect(existsSync(fileURLToPath(new URL("LICENSES.md", LIBRARY)))).toBe(true);
  });
});
