"""Generate the voice control cue sounds.

Run from the repository root with:
    python3 frontend/assets/voice/make-cues.py

Five 16 kHz mono 16-bit WAVs, each under 200 ms, written to cues/ beside this file.
They are generated rather than recorded so they carry no licence and can be
regenerated byte for byte. Each cue is a pair of sine tones with a short fade in and
out; the shape (rising, falling, doubled) is what makes them tell each other apart,
because a user hears them out of the corner of their ear while playing.

The file names match Voice::Cue (start, accept, reject, pending, cancel); VoiceFeedback
loads them from data/braidcast/voice/cues/, where the frontend's CMakeLists copies them
for the run directory and installs them for the package.
"""

import math
import os
import struct
import wave

RATE = 16000
# name -> (tones, gain). A tone is (frequency in Hz, milliseconds); 0 Hz is a gap.
CUES = {
    # Rising: the key registered, go ahead.
    "start": ([(660, 60), (880, 70)], 0.35),
    # Rising pair, brighter: it worked.
    "accept": ([(880, 55), (1170, 75)], 0.32),
    # Falling, lower: that did not match.
    "reject": ([(440, 70), (330, 90)], 0.30),
    # Level double tap: waiting on you.
    "pending": ([(740, 50), (0, 40), (740, 50)], 0.30),
    # Falling, short: dropped.
    "cancel": ([(520, 50), (390, 60)], 0.28),
}

FADE_MS = 8


def render(tones, gain):
    samples = []
    for freq, ms in tones:
        count = int(RATE * ms / 1000)
        fade = int(RATE * FADE_MS / 1000)
        for i in range(count):
            value = 0.0 if freq == 0 else math.sin(2.0 * math.pi * freq * i / RATE)
            envelope = 1.0
            if i < fade:
                envelope = i / fade
            elif i > count - fade:
                envelope = max(0.0, (count - i) / fade)
            samples.append(value * envelope * gain)
    return samples


def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cues")
    os.makedirs(out_dir, exist_ok=True)
    for name, (tones, gain) in CUES.items():
        path = os.path.join(out_dir, name + ".wav")
        samples = render(tones, gain)
        with wave.open(path, "wb") as out:
            out.setnchannels(1)
            out.setsampwidth(2)
            out.setframerate(RATE)
            out.writeframes(b"".join(struct.pack("<h", int(max(-1.0, min(1.0, s)) * 32767)) for s in samples))
        print("wrote {} ({} samples, {} ms)".format(path, len(samples), round(1000 * len(samples) / RATE)))


if __name__ == "__main__":
    main()
