// Bridge PUSH-EVENT names (subscribed via obs.on).
// Mirror of ../../../src/event_names.hpp -- values MUST match exactly.
export const EV = {
  streamProfileChanged: "streamProfile.changed",
  outputBindingChanged: "outputBinding.changed",
  canvasChanged: "canvas.changed",
  collectionsChanged: "collections.changed",
  streamingChanged: "streaming.changed",
  projectorChanged: "projector.changed",
  overlaysChanged: "overlays.changed",
  transitionsChanged: "transitions.changed",
  scenesChanged: "scenes.changed",
  sceneLinkChanged: "sceneLink.changed",
  mcpChanged: "mcp.changed",
  hotkeysChanged: "hotkeys.changed",
  audioChanged: "audio.changed",
  windowStateChanged: "window.stateChanged",
  windowClosed: "window.closed",
  windowOpened: "window.opened",
  settingsVideoChanged: "settings.videoChanged",
  settingsAudioChanged: "settings.audioChanged",
  settingsGeneralChanged: "settings.generalChanged",
  settingsAdvancedChanged: "settings.advancedChanged",
  screenshotSaved: "screenshot.saved",
  oauthStatus: "oauth.status",
  oauthConnectProgress: "oauth.connectProgress",
  oauthConnectError: "oauth.connectError",
  multistreamChanged: "multistream.changed",
  eventsNew: "events.new",
  eventsBackfill: "events.backfill",
  virtualCamChanged: "virtualCam.changed",
  undoChanged: "undo.changed",
  streamMetaChanged: "streamMeta.changed",
  sceneItemsChanged: "sceneItems.changed",
  sceneItemSelected: "sceneItem.selected",
  previewContextMenu: "preview.contextMenu",
  interactChanged: "interact.changed",
  chatState: "chat.state",
  chatMessage: "chat.message",
  channelsStats: "channels.stats",
  viewersChanged: "viewers.changed",
  audioLevels: "audio.levels",
  obsEvent: "obs.event",
} as const;

export type BridgeEvent = (typeof EV)[keyof typeof EV];
