#include "build_info.hpp"

#include "build_info.gen.h" // generated by cmake/gen-build-info.cmake into the build dir

namespace Braidcast {

const char *BuildDescribe()
{
	return BRAIDCAST_BUILD_DESCRIBE;
}

} // namespace Braidcast
